### PR TITLE
Fixed: pdf attachments were not visible in logs

### PR DESCRIPTION
**Pull request by protibimbok**

### CODE REVIEW

**Review by permafrost06 — CHANGES_REQUESTED** [review]
Make the modal larger. It takes up less than 30% of the viewport on my 1080p monitor.
image

**Comment by permafrost06** [comment]
> Make the modal larger. It takes up less than 30% of the viewport on my 1080p monitor.
[image]

Let know if this should be a separate pr. We should try to separate different fixes in its own pr. That way we can just look at the list of pr to see changes.

**Comment by protibimbok** [comment]
No as this is a part of the same bug, it should stay here...

**Comment by protibimbok** [comment]
> Make the modal larger. It takes up less than 30% of the viewport on my 1080p monitor.

How about 70% height of the screen?
image

**Comment by permafrost06** [comment]
> No as this is a part of the same bug, it should stay here...

I disagree, create a separate pr for this

**Review by permafrost06 — APPROVED** [review]
For now, this can be merged but a better fix (preferably in the modal CSS) should be implemented.

**Pull request merged**
