### PR TITLE
Added feature: stock-status attachment and remarks field

### LINKED ISSUE #11: Attachment and Remarks for Stock Status
Add columns for "Attachment" and "Remarks" in the Stock Status table. If there is no attachement or remark, user can add them. Note that these attachments and remarks are separate from the ones in the log. Ask questions if confused.

### PR DESCRIPTION
**Pull request by protibimbok**

### CODE REVIEW

**Comment by permafrost06** [comment]
Please mention when migration has to be re-run, or if some other command has to be run for the changes to work.

**Review by permafrost06 — CHANGES_REQUESTED** [review]
Modify the attachment column to show the "View" link only if attachment is present. Remove the upload button (see image below) from the view modal. Add a separate link "Edit" where the attachment can be changed (or added if it doesn't exist).
image

**Comment by protibimbok** [comment]
> Modify the attachment column to show the "View" link only if attachment is present.

image

How is this?

**Comment by protibimbok** [comment]
image
image

**Comment by permafrost06** [comment]
> > Modify the attachment column to show the "View" link only if attachment is present.
> 
> [image]
> 
> How is this?

These look good. “View” should only be shown if an attachment exists.

**Review by permafrost06 — APPROVED** [review]
LGTM

**Pull request merged**
