### PR TITLE
Feature added: stock cost functionalities

### LINKED ISSUE #13: Add cost calculations to stock functionality
1. To the stock entry form:

    1. add numeric field: "Unit Cost"
    2. add numeric field: "Adjustment"

1. To the stock logs table add a column "Cost". Calculation for Cost: `(Quantity) x (Unit Cost) + (Adjustment)`

1. To the stock status table add a column "Profit". Calculation for Profit: `(Total Out Cost) - (Total In Cost)`

When done implementing:
1. Add appropriate db seed data for testing. 
2. Add random data generator using factory to test with large random data.

### PR DESCRIPTION
**Pull request by protibimbok**

### CODE REVIEW

**Comment by permafrost06** [comment]
Please provide instructions for any commands that may need to be run

**Comment by permafrost06** [comment]
> @protibimbok: Please run `php artisan migrate:fresh --seed` before testing

**Review by permafrost06 — CHANGES_REQUESTED** [review]
There are way too many items seeded - it is difficult to verify the functionality. Seed db with 10 entries.
Don't generate completely random strings/numbers. Should follow the below rules:

- Item codes: `1001`, `1002`, `1003`
- Brand: `Charkha`, `Julahaa`, `Banarasi`
- Quantity: 100 - 500, multiple of 10
- Cost: 500/700/900
- Adjustment: -3000 to -5000
- There should be 3 merchants and 2 carriers with legible names. Their contacts are not necessary.
- Border, Remarks, Attachment will be empty

**Comment by protibimbok** [comment]
image
 Is this okay?

**Comment by protibimbok** [comment]
Again run the command `php artisan migrate:fresh --seed`

**Review by permafrost06 — CHANGES_REQUESTED** [review]
Add "Unit Cost" and "Adjustment" columns to Stock Logs
Rename "Cost" to "Total Cost"
"Adjustment" form field should be pre-filled with 0
"Adjustment" values in seeder should also be a multiple of 100

**Comment by permafrost06** [comment]
Check out #26. Let know if

- #26 should be fixed first or,
- modify the seeder to not create "out" stock entries with quantity higher than available quantity

Keep in mind, if that issue is resolved before this pr is merged, we may need to rebase. I don't know if we want that.

In my opinion, we should fix the seeder in this pr. Then, resolve #26.

**Comment by protibimbok** [comment]
I am currently seeding only `in` types. Because if I seed both `in` and `out` types then making them abide by these rules will require a lot of time. What do you say?

**Comment by permafrost06** [comment]
> I am currently seeding only `in` types. Because if I seed both `in` and `out` types then making them abide by these rules will require a lot of time. What do you say?

It'll do for now

**Comment by permafrost06** [comment]
> Add "Unit Cost" and "Adjustment" columns to Stock Logs Rename "Cost" to "Total Cost" "Adjustment" form field should be pre-filled with 0 "Adjustment" values in seeder should also be a multiple of 100

Please Add "Unit Cost" and "Adjustment" columns to Stock Logs and rename "Cost" to "Total Cost". Otherwise I have to query the database to verify the changes.

**Review by permafrost06 — COMMENTED** [review]
Please don't be ambiguous in commit messages in the future. If required, use multiples lines but "& more" is not helpful for anything.

**Comment by protibimbok** [comment]
Okay, is there anything else left to do?

**Review by permafrost06 — APPROVED** [review]

**Comment by permafrost06** [comment]
> Okay, is there anything else left to do?

Not for now

**Pull request merged**
